"""
View.IO SDK

This SDK provides a set of tools and functions to interact with the View.IO APIs. It simplifies the process of integrating View.IO's services into your application by making API requests, and processing responses.

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
from enum import Enum

from typing_extensions import Self


class ApiErrorEnum(str, Enum):
    """
    ApiErrorEnum
    """

    """
    allowed enum values
    """
    AUTHENTICATIONFAILED = "AuthenticationFailed"
    AUTHORIZATIONFAILED = "AuthorizationFailed"
    BADREQUEST = "BadRequest"
    CONFLICT = "Conflict"
    DESERIALIZATIONERROR = "DeserializationError"
    INACTIVE = "Inactive"
    INTERNALERROR = "InternalError"
    INVALIDRANGE = "InvalidRange"
    INUSE = "InUse"
    NOTEMPTY = "NotEmpty"
    NOTFOUND = "NotFound"
    TOOLARGE = "TooLarge"
    NOTYPEDETECTORCONNECTIVITY = "NoTypeDetectorConnectivity"
    UNKNOWNTYPEDETECTED = "UnknownTypeDetected"
    NOGRAPHCONNECTIVITY = "NoGraphConnectivity"
    GRAPHOPERATIONFAILED = "GraphOperationFailed"
    NOUDRCONNECTIVITY = "NoUdrConnectivity"
    UDRGENERATIONFAILED = "UdrGenerationFailed"
    NOSEMANTICCELLCONNECTIVITY = "NoSemanticCellConnectivity"
    SEMANTICCELLEXTRACTIONFAILED = "SemanticCellExtractionFailed"
    NODATACATALOGCONNECTIVITY = "NoDataCatalogConnectivity"
    DATACATALOGPERSISTFAILED = "DataCatalogPersistFailed"
    UNKNOWNDATACATALOGTYPE = "UnknownDataCatalogType"
    UNKNOWNEMBEDDINGSGENERATORTYPE = "UnknownEmbeddingsGeneratorType"
    EMBEDDINGSGENERATIONFAILED = "EmbeddingsGenerationFailed"
    EMBEDDINGSPERSISTFAILED = "EmbeddingsPersistFailed"
    NOOBJECTMETADATA = "NoObjectMetadata"
    NOOBJECTDATA = "NoObjectData"
    NOMETADATARULE = "NoMetadataRule"
    REQUIREDPROPERTIESMISSING = "RequiredPropertiesMissing"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ApiErrorEnum from a JSON string"""
        return cls(json.loads(json_str))
