"""
View.IO SDK

This SDK provides a set of tools and functions to interact with the View.IO APIs. It simplifies the process of integrating View.IO's services into your application by making API requests, and processing responses.

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing_extensions import Annotated, Self

from viewio_sdk.models.bucket_category_enum import BucketCategoryEnum
from viewio_sdk.models.user_master import UserMaster


class BucketMetadata(BaseModel):
    """
    BucketMetadata
    """  # noqa: E501

    id: Annotated[int, Field(strict=True, ge=1)] | None = Field(
        default=None, alias="Id"
    )
    guid: StrictStr | None = Field(default=None, alias="GUID")
    tenant_guid: StrictStr | None = Field(default=None, alias="TenantGUID")
    pool_guid: StrictStr | None = Field(default=None, alias="PoolGUID")
    owner_guid: StrictStr | None = Field(default=None, alias="OwnerGUID")
    category: BucketCategoryEnum | None = Field(default=None, alias="Category")
    name: StrictStr | None = Field(default="", alias="Name")
    region_string: StrictStr | None = Field(default="us-west-1", alias="RegionString")
    versioning: StrictBool | None = Field(default=True, alias="Versioning")
    retention_minutes: Annotated[int, Field(strict=True, ge=1)] | None = Field(
        default=None, alias="RetentionMinutes"
    )
    max_upload_size: StrictInt | None = Field(default=None, alias="MaxUploadSize")
    max_multipart_upload_seconds: StrictInt | None = Field(
        default=604800, alias="MaxMultipartUploadSeconds"
    )
    last_access_utc: datetime | None = Field(default=None, alias="LastAccessUtc")
    created_utc: datetime | None = Field(default=None, alias="CreatedUtc")
    owner: UserMaster | None = Field(default=None, alias="Owner")
    __properties: ClassVar[list[str]] = [
        "Id",
        "GUID",
        "TenantGUID",
        "PoolGUID",
        "OwnerGUID",
        "Category",
        "Name",
        "RegionString",
        "Versioning",
        "RetentionMinutes",
        "MaxUploadSize",
        "MaxMultipartUploadSeconds",
        "LastAccessUtc",
        "CreatedUtc",
        "Owner",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of BucketMetadata from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set()

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of owner
        if self.owner:
            _dict["Owner"] = self.owner.to_dict()
        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict["Id"] = None

        # set to None if retention_minutes (nullable) is None
        # and model_fields_set contains the field
        if (
            self.retention_minutes is None
            and "retention_minutes" in self.model_fields_set
        ):
            _dict["RetentionMinutes"] = None

        # set to None if max_upload_size (nullable) is None
        # and model_fields_set contains the field
        if self.max_upload_size is None and "max_upload_size" in self.model_fields_set:
            _dict["MaxUploadSize"] = None

        # set to None if owner (nullable) is None
        # and model_fields_set contains the field
        if self.owner is None and "owner" in self.model_fields_set:
            _dict["Owner"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of BucketMetadata from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "Id": obj.get("Id"),
                "GUID": obj.get("GUID"),
                "TenantGUID": obj.get("TenantGUID"),
                "PoolGUID": obj.get("PoolGUID"),
                "OwnerGUID": obj.get("OwnerGUID"),
                "Category": obj.get("Category"),
                "Name": obj.get("Name") if obj.get("Name") is not None else "",
                "RegionString": obj.get("RegionString")
                if obj.get("RegionString") is not None
                else "us-west-1",
                "Versioning": obj.get("Versioning")
                if obj.get("Versioning") is not None
                else True,
                "RetentionMinutes": obj.get("RetentionMinutes"),
                "MaxUploadSize": obj.get("MaxUploadSize"),
                "MaxMultipartUploadSeconds": obj.get("MaxMultipartUploadSeconds")
                if obj.get("MaxMultipartUploadSeconds") is not None
                else 604800,
                "LastAccessUtc": obj.get("LastAccessUtc"),
                "CreatedUtc": obj.get("CreatedUtc"),
                "Owner": UserMaster.from_dict(obj["Owner"])
                if obj.get("Owner") is not None
                else None,
            }
        )
        return _obj
