"""
View.IO SDK

This SDK provides a set of tools and functions to interact with the View.IO APIs. It simplifies the process of integrating View.IO's services into your application by making API requests, and processing responses.

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing_extensions import Annotated, Self

from viewio_sdk.models.embeddings_generator_enum import EmbeddingsGeneratorEnum


class EmbeddingsRule(BaseModel):
    """
    EmbeddingsRule
    """  # noqa: E501

    guid: StrictStr | None = Field(default=None, alias="GUID")
    tenant_guid: StrictStr | None = Field(default=None, alias="TenantGUID")
    bucket_guid: StrictStr | None = Field(default=None, alias="BucketGUID")
    owner_guid: StrictStr | None = Field(default=None, alias="OwnerGUID")
    name: StrictStr | None = Field(default=None, alias="Name")
    content_type: StrictStr | None = Field(default="text/plain", alias="ContentType")
    prefix: StrictStr | None = Field(default=None, alias="Prefix")
    suffix: StrictStr | None = Field(default=None, alias="Suffix")
    target_bucket_guid: StrictStr | None = Field(default=None, alias="TargetBucketGUID")
    graph_repository_guid: StrictStr | None = Field(
        default=None, alias="GraphRepositoryGUID"
    )
    vector_repository_guid: StrictStr | None = Field(
        default=None, alias="VectorRepositoryGUID"
    )
    data_flow_endpoint: StrictStr | None = Field(
        default="http://localhost:8501/processor", alias="DataFlowEndpoint"
    )
    embeddings_generator: EmbeddingsGeneratorEnum | None = Field(
        default=None, alias="EmbeddingsGenerator"
    )
    generator_url: StrictStr | None = Field(
        default="http://localhost:8301/", alias="GeneratorUrl"
    )
    generator_api_key: StrictStr | None = Field(default=None, alias="GeneratorApiKey")
    batch_size: Annotated[int, Field(strict=True, ge=1)] | None = Field(
        default=16, alias="BatchSize"
    )
    max_generator_tasks: Annotated[int, Field(strict=True, ge=1)] | None = Field(
        default=16, alias="MaxGeneratorTasks"
    )
    max_retries: Annotated[int, Field(strict=True, ge=1)] | None = Field(
        default=3, alias="MaxRetries"
    )
    max_failures: Annotated[int, Field(strict=True, ge=1)] | None = Field(
        default=3, alias="MaxFailures"
    )
    vector_store_url: StrictStr | None = Field(
        default="http://localhost:8311/", alias="VectorStoreUrl"
    )
    max_content_length: Annotated[int, Field(strict=True, ge=1)] | None = Field(
        default=16777216, alias="MaxContentLength"
    )
    retention_minutes: Annotated[int, Field(strict=True, ge=1)] | None = Field(
        default=None, alias="RetentionMinutes"
    )
    created_utc: datetime | None = Field(default=None, alias="CreatedUtc")
    __properties: ClassVar[list[str]] = [
        "GUID",
        "TenantGUID",
        "BucketGUID",
        "OwnerGUID",
        "Name",
        "ContentType",
        "Prefix",
        "Suffix",
        "TargetBucketGUID",
        "GraphRepositoryGUID",
        "VectorRepositoryGUID",
        "DataFlowEndpoint",
        "EmbeddingsGenerator",
        "GeneratorUrl",
        "GeneratorApiKey",
        "BatchSize",
        "MaxGeneratorTasks",
        "MaxRetries",
        "MaxFailures",
        "VectorStoreUrl",
        "MaxContentLength",
        "RetentionMinutes",
        "CreatedUtc",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of EmbeddingsRule from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set()

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if tenant_guid (nullable) is None
        # and model_fields_set contains the field
        if self.tenant_guid is None and "tenant_guid" in self.model_fields_set:
            _dict["TenantGUID"] = None

        # set to None if bucket_guid (nullable) is None
        # and model_fields_set contains the field
        if self.bucket_guid is None and "bucket_guid" in self.model_fields_set:
            _dict["BucketGUID"] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict["Name"] = None

        # set to None if prefix (nullable) is None
        # and model_fields_set contains the field
        if self.prefix is None and "prefix" in self.model_fields_set:
            _dict["Prefix"] = None

        # set to None if suffix (nullable) is None
        # and model_fields_set contains the field
        if self.suffix is None and "suffix" in self.model_fields_set:
            _dict["Suffix"] = None

        # set to None if target_bucket_guid (nullable) is None
        # and model_fields_set contains the field
        if (
            self.target_bucket_guid is None
            and "target_bucket_guid" in self.model_fields_set
        ):
            _dict["TargetBucketGUID"] = None

        # set to None if graph_repository_guid (nullable) is None
        # and model_fields_set contains the field
        if (
            self.graph_repository_guid is None
            and "graph_repository_guid" in self.model_fields_set
        ):
            _dict["GraphRepositoryGUID"] = None

        # set to None if vector_repository_guid (nullable) is None
        # and model_fields_set contains the field
        if (
            self.vector_repository_guid is None
            and "vector_repository_guid" in self.model_fields_set
        ):
            _dict["VectorRepositoryGUID"] = None

        # set to None if generator_api_key (nullable) is None
        # and model_fields_set contains the field
        if (
            self.generator_api_key is None
            and "generator_api_key" in self.model_fields_set
        ):
            _dict["GeneratorApiKey"] = None

        # set to None if retention_minutes (nullable) is None
        # and model_fields_set contains the field
        if (
            self.retention_minutes is None
            and "retention_minutes" in self.model_fields_set
        ):
            _dict["RetentionMinutes"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of EmbeddingsRule from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "GUID": obj.get("GUID"),
                "TenantGUID": obj.get("TenantGUID"),
                "BucketGUID": obj.get("BucketGUID"),
                "OwnerGUID": obj.get("OwnerGUID"),
                "Name": obj.get("Name"),
                "ContentType": obj.get("ContentType")
                if obj.get("ContentType") is not None
                else "text/plain",
                "Prefix": obj.get("Prefix"),
                "Suffix": obj.get("Suffix"),
                "TargetBucketGUID": obj.get("TargetBucketGUID"),
                "GraphRepositoryGUID": obj.get("GraphRepositoryGUID"),
                "VectorRepositoryGUID": obj.get("VectorRepositoryGUID"),
                "DataFlowEndpoint": obj.get("DataFlowEndpoint")
                if obj.get("DataFlowEndpoint") is not None
                else "http://localhost:8501/processor",
                "EmbeddingsGenerator": obj.get("EmbeddingsGenerator"),
                "GeneratorUrl": obj.get("GeneratorUrl")
                if obj.get("GeneratorUrl") is not None
                else "http://localhost:8301/",
                "GeneratorApiKey": obj.get("GeneratorApiKey"),
                "BatchSize": obj.get("BatchSize")
                if obj.get("BatchSize") is not None
                else 16,
                "MaxGeneratorTasks": obj.get("MaxGeneratorTasks")
                if obj.get("MaxGeneratorTasks") is not None
                else 16,
                "MaxRetries": obj.get("MaxRetries")
                if obj.get("MaxRetries") is not None
                else 3,
                "MaxFailures": obj.get("MaxFailures")
                if obj.get("MaxFailures") is not None
                else 3,
                "VectorStoreUrl": obj.get("VectorStoreUrl")
                if obj.get("VectorStoreUrl") is not None
                else "http://localhost:8311/",
                "MaxContentLength": obj.get("MaxContentLength")
                if obj.get("MaxContentLength") is not None
                else 16777216,
                "RetentionMinutes": obj.get("RetentionMinutes"),
                "CreatedUtc": obj.get("CreatedUtc"),
            }
        )
        return _obj
