"""
View.IO SDK

This SDK provides a set of tools and functions to interact with the View.IO APIs. It simplifies the process of integrating View.IO's services into your application by making API requests, and processing responses.

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing_extensions import Annotated, Self

from viewio_sdk.models.graph_repository_type_enum import GraphRepositoryTypeEnum


class GraphRepository(BaseModel):
    """
    GraphRepository
    """  # noqa: E501

    guid: StrictStr | None = Field(default=None, alias="GUID")
    tenant_guid: StrictStr | None = Field(default=None, alias="TenantGUID")
    name: StrictStr | None = Field(default="My vector repository", alias="Name")
    repository_type: GraphRepositoryTypeEnum | None = Field(
        default=None, alias="RepositoryType"
    )
    endpoint_url: StrictStr | None = Field(default=None, alias="EndpointUrl")
    api_key: StrictStr | None = Field(default=None, alias="ApiKey")
    username: StrictStr | None = Field(default=None, alias="Username")
    password: StrictStr | None = Field(default=None, alias="Password")
    hostname: StrictStr | None = Field(default=None, alias="Hostname")
    port: Annotated[int, Field(le=65535, strict=True, ge=0)] | None = Field(
        default=0, alias="Port"
    )
    graph_identifier: StrictStr | None = Field(default=None, alias="GraphIdentifier")
    created_utc: datetime | None = Field(default=None, alias="CreatedUtc")
    __properties: ClassVar[list[str]] = [
        "GUID",
        "TenantGUID",
        "Name",
        "RepositoryType",
        "EndpointUrl",
        "ApiKey",
        "Username",
        "Password",
        "Hostname",
        "Port",
        "GraphIdentifier",
        "CreatedUtc",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of GraphRepository from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set()

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if endpoint_url (nullable) is None
        # and model_fields_set contains the field
        if self.endpoint_url is None and "endpoint_url" in self.model_fields_set:
            _dict["EndpointUrl"] = None

        # set to None if api_key (nullable) is None
        # and model_fields_set contains the field
        if self.api_key is None and "api_key" in self.model_fields_set:
            _dict["ApiKey"] = None

        # set to None if username (nullable) is None
        # and model_fields_set contains the field
        if self.username is None and "username" in self.model_fields_set:
            _dict["Username"] = None

        # set to None if password (nullable) is None
        # and model_fields_set contains the field
        if self.password is None and "password" in self.model_fields_set:
            _dict["Password"] = None

        # set to None if hostname (nullable) is None
        # and model_fields_set contains the field
        if self.hostname is None and "hostname" in self.model_fields_set:
            _dict["Hostname"] = None

        # set to None if graph_identifier (nullable) is None
        # and model_fields_set contains the field
        if (
            self.graph_identifier is None
            and "graph_identifier" in self.model_fields_set
        ):
            _dict["GraphIdentifier"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of GraphRepository from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "GUID": obj.get("GUID"),
                "TenantGUID": obj.get("TenantGUID"),
                "Name": obj.get("Name")
                if obj.get("Name") is not None
                else "My vector repository",
                "RepositoryType": obj.get("RepositoryType"),
                "EndpointUrl": obj.get("EndpointUrl"),
                "ApiKey": obj.get("ApiKey"),
                "Username": obj.get("Username"),
                "Password": obj.get("Password"),
                "Hostname": obj.get("Hostname"),
                "Port": obj.get("Port") if obj.get("Port") is not None else 0,
                "GraphIdentifier": obj.get("GraphIdentifier"),
                "CreatedUtc": obj.get("CreatedUtc"),
            }
        )
        return _obj
