"""
View.IO SDK

This SDK provides a set of tools and functions to interact with the View.IO APIs. It simplifies the process of integrating View.IO's services into your application by making API requests, and processing responses.

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing_extensions import Self


class UserMaster(BaseModel):
    """
    UserMaster
    """  # noqa: E501

    guid: StrictStr | None = Field(default=None, alias="GUID")
    tenant_guid: StrictStr | None = Field(default=None, alias="TenantGUID")
    first_name: StrictStr | None = Field(default="", alias="FirstName")
    last_name: StrictStr | None = Field(default="", alias="LastName")
    full_name: StrictStr | None = Field(default=None, alias="FullName")
    notes: StrictStr | None = Field(default=None, alias="Notes")
    email: StrictStr | None = Field(default="", alias="Email")
    password_sha256: StrictStr | None = Field(default="", alias="PasswordSha256")
    active: StrictBool | None = Field(default=True, alias="Active")
    created_utc: datetime | None = Field(default=None, alias="CreatedUtc")
    __properties: ClassVar[list[str]] = [
        "GUID",
        "TenantGUID",
        "FirstName",
        "LastName",
        "FullName",
        "Notes",
        "Email",
        "PasswordSha256",
        "Active",
        "CreatedUtc",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of UserMaster from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set()

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if full_name (nullable) is None
        # and model_fields_set contains the field
        if self.full_name is None and "full_name" in self.model_fields_set:
            _dict["FullName"] = None

        # set to None if notes (nullable) is None
        # and model_fields_set contains the field
        if self.notes is None and "notes" in self.model_fields_set:
            _dict["Notes"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of UserMaster from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "GUID": obj.get("GUID"),
                "TenantGUID": obj.get("TenantGUID"),
                "FirstName": obj.get("FirstName")
                if obj.get("FirstName") is not None
                else "",
                "LastName": obj.get("LastName")
                if obj.get("LastName") is not None
                else "",
                "FullName": obj.get("FullName"),
                "Notes": obj.get("Notes"),
                "Email": obj.get("Email") if obj.get("Email") is not None else "",
                "PasswordSha256": obj.get("PasswordSha256")
                if obj.get("PasswordSha256") is not None
                else "",
                "Active": obj.get("Active") if obj.get("Active") is not None else True,
                "CreatedUtc": obj.get("CreatedUtc"),
            }
        )
        return _obj
