"""
View.IO SDK

This SDK provides a set of tools and functions to interact with the View.IO APIs. It simplifies the process of integrating View.IO's services into your application by making API requests, and processing responses.

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing_extensions import Annotated, Self

from viewio_sdk.models.webhook_event_type_enum import WebhookEventTypeEnum


class WebhookEvent(BaseModel):
    """
    WebhookEvent
    """  # noqa: E501

    guid: StrictStr | None = Field(default=None, alias="GUID")
    tenant_guid: StrictStr | None = Field(default=None, alias="TenantGUID")
    target_guid: StrictStr | None = Field(default=None, alias="TargetGUID")
    rule_guid: StrictStr | None = Field(default=None, alias="RuleGUID")
    event_type: WebhookEventTypeEnum | None = Field(default=None, alias="EventType")
    content_length: Annotated[int, Field(strict=True, ge=0)] | None = Field(
        default=0, alias="ContentLength"
    )
    timeout_ms: Annotated[int, Field(strict=True, ge=1)] | None = Field(
        default=60000, alias="TimeoutMs"
    )
    url: Annotated[str, Field(min_length=1, strict=True, max_length=2083)] = Field(
        alias="Url"
    )
    content_type: StrictStr | None = Field(
        default="application/json", alias="ContentType"
    )
    expect_status: Annotated[int, Field(le=599, strict=True, ge=100)] | None = Field(
        default=200, alias="ExpectStatus"
    )
    retry_interval_ms: Annotated[int, Field(strict=True, ge=1)] | None = Field(
        default=10000, alias="RetryIntervalMs"
    )
    attempt: Annotated[int, Field(strict=True, ge=0)] | None = Field(
        default=0, alias="Attempt"
    )
    max_attempts: Annotated[int, Field(strict=True, ge=1)] | None = Field(
        default=5, alias="MaxAttempts"
    )
    http_status: Annotated[int, Field(le=599, strict=True, ge=0)] | None = Field(
        default=0, alias="HttpStatus"
    )
    created_utc: datetime | None = Field(default=None, alias="CreatedUtc")
    added_utc: datetime | None = Field(default=None, alias="AddedUtc")
    last_attempt_utc: datetime | None = Field(default=None, alias="LastAttemptUtc")
    next_attempt_utc: datetime | None = Field(default=None, alias="NextAttemptUtc")
    last_failure_utc: datetime | None = Field(default=None, alias="LastFailureUtc")
    success_utc: datetime | None = Field(default=None, alias="SuccessUtc")
    failed_utc: datetime | None = Field(default=None, alias="FailedUtc")
    __properties: ClassVar[list[str]] = [
        "GUID",
        "TenantGUID",
        "TargetGUID",
        "RuleGUID",
        "EventType",
        "ContentLength",
        "TimeoutMs",
        "Url",
        "ContentType",
        "ExpectStatus",
        "RetryIntervalMs",
        "Attempt",
        "MaxAttempts",
        "HttpStatus",
        "CreatedUtc",
        "AddedUtc",
        "LastAttemptUtc",
        "NextAttemptUtc",
        "LastFailureUtc",
        "SuccessUtc",
        "FailedUtc",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of WebhookEvent from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set()

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if last_attempt_utc (nullable) is None
        # and model_fields_set contains the field
        if (
            self.last_attempt_utc is None
            and "last_attempt_utc" in self.model_fields_set
        ):
            _dict["LastAttemptUtc"] = None

        # set to None if next_attempt_utc (nullable) is None
        # and model_fields_set contains the field
        if (
            self.next_attempt_utc is None
            and "next_attempt_utc" in self.model_fields_set
        ):
            _dict["NextAttemptUtc"] = None

        # set to None if last_failure_utc (nullable) is None
        # and model_fields_set contains the field
        if (
            self.last_failure_utc is None
            and "last_failure_utc" in self.model_fields_set
        ):
            _dict["LastFailureUtc"] = None

        # set to None if success_utc (nullable) is None
        # and model_fields_set contains the field
        if self.success_utc is None and "success_utc" in self.model_fields_set:
            _dict["SuccessUtc"] = None

        # set to None if failed_utc (nullable) is None
        # and model_fields_set contains the field
        if self.failed_utc is None and "failed_utc" in self.model_fields_set:
            _dict["FailedUtc"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of WebhookEvent from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "GUID": obj.get("GUID"),
                "TenantGUID": obj.get("TenantGUID"),
                "TargetGUID": obj.get("TargetGUID"),
                "RuleGUID": obj.get("RuleGUID"),
                "EventType": obj.get("EventType"),
                "ContentLength": obj.get("ContentLength")
                if obj.get("ContentLength") is not None
                else 0,
                "TimeoutMs": obj.get("TimeoutMs")
                if obj.get("TimeoutMs") is not None
                else 60000,
                "Url": obj.get("Url"),
                "ContentType": obj.get("ContentType")
                if obj.get("ContentType") is not None
                else "application/json",
                "ExpectStatus": obj.get("ExpectStatus")
                if obj.get("ExpectStatus") is not None
                else 200,
                "RetryIntervalMs": obj.get("RetryIntervalMs")
                if obj.get("RetryIntervalMs") is not None
                else 10000,
                "Attempt": obj.get("Attempt") if obj.get("Attempt") is not None else 0,
                "MaxAttempts": obj.get("MaxAttempts")
                if obj.get("MaxAttempts") is not None
                else 5,
                "HttpStatus": obj.get("HttpStatus")
                if obj.get("HttpStatus") is not None
                else 0,
                "CreatedUtc": obj.get("CreatedUtc"),
                "AddedUtc": obj.get("AddedUtc"),
                "LastAttemptUtc": obj.get("LastAttemptUtc"),
                "NextAttemptUtc": obj.get("NextAttemptUtc"),
                "LastFailureUtc": obj.get("LastFailureUtc"),
                "SuccessUtc": obj.get("SuccessUtc"),
                "FailedUtc": obj.get("FailedUtc"),
            }
        )
        return _obj
